### ISSUE TITLE
Tests are taking too long in development

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#421]
It's fairly natural that our tests will start taking longer to run the more code we have, but I've noticed a dramatic increase in the time taken recently. 

This ticket is to help us figure out what's slowing us down and whether there's anything we can do to speed our development process up. This ticket encompases both unit + behaviour testing.

As part of this ticket you should investigate:

- [x] Which tests (or groups of tests) are taking the longest to run
  - [x] Whether there are any similarities between tests which are taking a long time
- [x] Is there anything we can do to speed up any of our tests? 
- [x] Figure out whether there are a sensible set of groups of tests we could defer to execution on pull requests/merges to main that devs could avoid running on their local boxes (if they haven't touched the code).  

If you have any other suggestions which you think might help reduce the need to run quite so many tests locally, bring them up as part of this ticket.

N.B. actually implementing any of these suggestions is outside of this ticket - you'll need to create the tickets once we've agreed on the approach we'll want to take (if any).

See the comments as part this ticket for existing suggestions of what to do - please propose any new ideas you have as a result of this investigation.

On completion of this ticket you will have created some new tickets (probably spikes) to investigate your suggested courses of action.

**Comment by canwaf** [comment]
* pytest-bdd

**Comment by GDonRanasinghe** [comment]
We need to reduce the size of CSV datasets in the test cases folder. Challenge is how we can do this whilst making sure the unit tests are still meaningful (i.e. covers the real-world scenario).

**Comment by GDonRanasinghe** [comment]
And yes I agree with Andrew on pytest-bdd. So we can keep unit and bdd tests within the same framework - will look good on IDEs too.

**Comment by robons** [comment]
As of today's refinement meeting, here are our initial thoughts on how we can speed stuff up:

## Short Term
- Do we use Swirrl's AOT-compile version of csv2rdf in our docker image -- will this speed things up enough for now?
- What are we really using csv2rdf for? Is this something that can be replaced by direct queries to the JSON-LD metadata files? 

## Longer Term Solutions

- How frequently are we running the SPARQL tests -- is it worth investing effort in rewriting them so they work against the CSV-W?
- pytest-bdd -- will speed things up at all? Parralelisation -- can we configure this so it runs 4 processes locally but only 1 on Jenkins to avoid resource problems?


- Andrew G suggested - could we keep a long-running docker container open for csv2rdf so we don't deal with the startup times problem so much?

**Comment by canwaf** [comment]
A quick summary of the length of time it takes to run the pytest suite (top 20 longest tests).

The 20 least performant tests are 62s of approximately 102s on my machine. Improving the performance of our pytest testing suite doesn't feel like a good use of time. The majority address the inspect command, which could be slimmed down to a few BDD tests, but whether that refactoring would save us anytime is questionable.

```text
===================================================================== slowest 20 durations =====================================================================
5.83s call     tests/unit/cli/inspect/test_inspectdatasetmanager.py::test_get_val_counts_info_single_unit_multi_measure_dataset
5.79s call     tests/unit/cli/inspect/test_inspectdatasetmanager.py::test_get_measure_col_name_from_dsd_measure_col_not_present
5.66s call     tests/unit/cli/inspect/test_inspectdatasetmanager.py::test_get_val_counts_info_multi_unit_single_measure_dataset
5.58s call     tests/unit/cli/inspect/test_inspectdatasetmanager.py::test_get_single_measure_label_from_dsd
5.56s call     tests/unit/cli/inspect/test_inspectdatasetmanager.py::test_get_unit_col_name_from_dsd_unit_col_not_present
5.22s call     tests/unit/cli/inspect/test_inspectsparqlmanager.py::test_select_single_unit_from_dsd
4.97s call     tests/unit/cli/inspect/test_metadatainputvalidator.py::test_detect_valid_csvw_metadata_datacube_input
2.58s call     tests/unit/cli/inspect/test_inspectdatasetmanager.py::test_get_measure_col_name_from_dsd_measure_col_present
2.06s call     tests/unit/cli/inspect/test_inspectdatasetmanager.py::test_get_unit_col_name_from_dsd_unit_col_present
2.03s call     tests/unit/cli/inspect/test_inspectdatasetmanager.py::test_get_val_counts_info_multi_unit_multi_measure_dataset
2.00s call     tests/unit/cli/inspect/test_inspectsparqlmanager.py::test_select_csvw_dsd_dataset
1.79s call     tests/unit/cli/inspect/test_inspectsparqlmanager.py::test_select_csvw_catalog_metadata_for_dataset
1.78s call     tests/unit/cli/inspect/test_inspectsparqlmanager.py::test_ask_is_csvw_qb_dataset
1.77s call     tests/unit/cli/inspect/test_metadataprocessor.py::test_metadata_dataset_json_ld_to_rdf_loading
1.76s call     tests/unit/cli/inspect/test_metadatainputvalidator.py::test_detect_type_datacube
1.75s call     tests/unit/cli/inspect/test_inspectsparqlmanager.py::test_select_cols_when_supress_output_cols_not_present
1.75s call     tests/unit/cli/inspect/test_inspectsparqlmanager.py::test_select_cols_when_supress_output_cols_present
1.72s call     tests/unit/cli/inspect/test_metadataprocessor.py::test_metadata_dataset_json_ld_to_rdf_loading_when_path_contains_url_encodable_chars
1.72s call     tests/unit/cli/inspect/test_inspectsparqlmanager.py::test_select_qb_dataset_url
1.72s call     tests/unit/cli/inspect/test_inspectsparqlmanager.py::test_select_dsd_code_list_and_cols_without_codelist_labels
========================================================== 231 passed, 9 warnings in 99.21s (0:01:39) ==========================================================
```

**Comment by canwaf** [comment]
```bash
time behave tests/behaviour --tags=-skip -kmq
```

```
7 features passed, 0 failed, 0 skipped
47 scenarios passed, 0 failed, 0 skipped
314 steps passed, 0 failed, 0 skipped, 0 undefined
Took 3m1.266s
behave tests/behaviour --tags=-skip -kmq  11.69s user 1.26s system 3% cpu 5:52.48 total
```

**Comment by canwaf** [comment]
## BDD Scenario analysis
The goal of this test is to check which BDD tests might be repeating steps unnecessarily. Again, considering we got behave tests twice as fast by using a native-AOT csv2rdf docker image there's diminishing returns here. A lot of tests which use csv2rdf are checks if a specific qube is still valid at lint and after RDF serialisation. Many of these can be consolidated, conceivably by creating fewer scenarios which contain the individual features in a single cube.

Summary of csv2rdf calls in feature files (23 total)
* 19 in qbwriter
* 2 in skoscodelists
* 2 in dcatcommandline

Note that none of these steps are expected to fail, so a "monster test case" might be possible unless testing data shape differences (i.e. single or multi measure). Additionally, you cannot consolidate testing for failures, since you want to see a specific failure, opposed to any failure.

## qbwriter.feature
This following table summaries the state of qbwriter's features which use csv2rdf. Consolidation is possible into a minimum of two tests in a "monster" qube.

| Scenario Name                                                                                              | Single, Multi, or Not Relevant | Consolidation possible |
|------------------------------------------------------------------------------------------------------------|--------------------------------|------------------------|
| A QbCube should generate appropriate DCAT Metadata                                                         | Not relevant                   | Yes                    |
| A QbCube should validate successfully where foreign key constraints are met.                               | Not relevant                   | Yes                    |
| QbCube new attribute values and units should be serialised                                                 | Not relevant                   | Yes                    |
| QbCube extended units (and new base units) should be serialised correctly.                                 | Not relevant                   | Yes                    |
| A QbCube with string literal new attributes should validate successfully                                   | Not relevant                   | Yes                    |
| A QbCube with numeric literal new attributes should validate successfully                                  | Not relevant                   | Yes                    |
| A QbCube with date literal new attributes should validate successfully                                     | Not relevant                   | Yes                    |
| A QbCube with string literal existing attributes should validate successfully                              | Not relevant                   | Yes                    |
| A QbCube with numeric literal existing attributes should validate successfully                             | Not relevant                   | Yes                    |
| A QbCube with date literal existing attributes should validate successfully                                | Not relevant                   | Yes                    |
| A single-measure QbCube should pass skos+qb SPARQL test constraints                                        | Single                         | Yes                    |
| A multi-measure QbCube should pass skos+qb SPARQL test constraints                                         | Multi                          | Yes                    |
| A locally defined single-measure dataset (with code-lists) can be serialised to a standard CSV-qb          | Single                         | Yes                    |
| A locally defined multi-measure dataset (with code-lists) can be serialised to a standard CSV-qb           | Multi                          | Yes                    |
| A single-measure dataset (with code-list) having existing resources can be serialised to a standard CSV-qb | Single                         | Yes                    |
| A multi-measure dataset (with code-list) having existing resources can be serialised to a standard CSV-qb  | Multi                          | Yes                    |
| A codelist defined in a CSV-W should be copied to the output directory                                     | Not relevant                   | Yes                    |
| Each Observation should have Type http://purl.org/linked-data/cube#Observation and be part of the dataset  | Not relevant                   | Yes                    |
| A QbCube which references a legacy composite code list should pass all tests                               | Not relevant                   | Yes                    |

The csv2rdf steps in `qbwriter.feature` take 103 of 160 seconds for this specific feature file run on my laptop at this time. So, over two thirds of the time.

## Conclusion
Consolidating long running tests into a single feature test or a few feature tests could result in a third reduction of a specific feature's runtime. 

## Recommendation
Monitor

**Comment by canwaf** [comment]
## Jenkins build analysis
### Scope
Looking at only steps in the last 8 successful builds which take longer than a minute for potential improvements. Total Jenkins pipeline appears to be decreasing from an average of 17 minutes to recent builds of approximately 12ish.

### Results
#### Docker build of environment
The docker container build step takes an average of 3:18, lowest being below a minute, highest 5:16.
**conclusion** building the docker image is the single most costly action in the Jenkins pipeline
**recommendation** use a docker image instead of building from the docker file each time. This image should have poetry installed, so that we only need to use poetry install to run tests, etc.

### csvcubed behave tests
The behave tests on csvcubed take between 2:36 and 10:00, with an average of 6:19, which appears to be decreasing (with the new AOT compiler).
**conclusion** AOT compiled will speed things up
**recommendation** monitor

### csvcubed qbwriter.feature
The csv2rdf function does take the majority of the behave test time, but with adopting AOT test time is already decreased. We can reduce the time it takes to check if cubes are valid (i.e. no feature backslipping) by combining tests into a [monster cube](https://github.com/GSS-Cogs/csvcubed/issues/421#issuecomment-1117266468) might work, but likely won't be necessary.


### csvcubed unit tests
The unit tests on csvcubed take between 1:28 and 1:48, with an average of 1:36, which appears stable.
**conclusion** unit tests are already fast
**recommendation** monitor

## Conclusion
There is not much lower fruit here for optimisation.

## Recommendations
- [x] Adopt AOT csv2rdf
- [ ] Raise monster cube ticket based on [this comment](https://github.com/GSS-Cogs/csvcubed/issues/421#issuecomment-1117266468)
- [ ] Move to a pre-build docker image to run our tests, build this image when the Dockerfile changes or when a new base-image is released, set Jenkins to pull this image instead of building it
- [ ] Moving to multiple-repos will speed up changes to specific packages (by testing less)
- [ ] Use GitHub Actions for stuff which can be pulled off the Jenkins runner which don't depend on CICD (i.e. build and publish docs only on tagged releases)
- [ ] CICD and test monitoring suites which track performance will improve metrics and allow us to focus on individual problems (See #425)

**Comment by robons** [comment]
>  i.e. build and publish docs only on tagged releases

I'm not 100% in support of this. There are things you can do to break the documentation build -- I'd rather that be highlighted in a PR build rather than saving all those broken things up until when we release.

**Comment by robons** [comment]
> Raise monster cube ticket based on https://github.com/GSS-Cogs/csvcubed/issues/421#issuecomment-1117266468

I'm very much against creating a monster test, however (as I think we've discussed), I think there may be scope to speed some of these tests up by removing the need to run csv2rdf at all and instead running all RDF assertions against the CSV-W metadata document -- obviously this will only work where the metadata we're checking isn't generated from the CSV by csv2rdf itself.

> Move to a pre-build docker image to run our tests, build this image when the Dockerfile changes or when a new base-image is released, set Jenkins to pull this image instead of building it

We can do this to a point, but we should still have Jenkins build a new image (on top of some standardised python 3.10 base image) so that it can use the pyproject.toml/poetry.lock files to install all of the dependencies in a cached fashion.

**Comment by canwaf** [comment]
Yup. The base Docker image can be stored and sent to Docker hub but the Python environment beyond a Python distribution + poetry needs to be built each time.

We agree.

A way of querying CSVW as if it were RDF serialised would be a good project to throw at Swirrl.
