### ISSUE TITLE
Investigate using github actions instead of Jenkins pipelines.

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#433]
- [x] We currently have a security concern over whether users could run arbitrary code/exfiltrate secrets from our github pipeline if they were to create a PR.

We likely either need to: 

- Ensure that external users cannot create PRs (to avoid exfiltrating secrets)
- Or: ensure the deployment secrets (e.g. API keys to publishing to PMD, etc.) can be effectively isolated and inaccessible to PRs created by external users. 

Someone else will likely have already solved this problem somewhere on the internet, so that would be a good starting point for this ticket.

We should make sure to apply whatever restrictions we decide on in this ticket to *all* repositories in the GSS-Cogs organisation.

- [x] More thorough think about our github repos and making sure there’s no other way we could accidentally end up letting users waste our resources and letting them exfiltrate secrets.

- [x] Identify whether there is an equivalent for presenting unit and behave test results in a meaningful way like in Jenkins.

- [x] Identify any rate limits.

- [x] Create a presentation summarising the findings for discussing at the architectural meeting.

 **N.B. this almost certainly needs discussion with the wider team in the architectural meeting/the monthly (?) tech board before progressing.**

**Comment by GDonRanasinghe** [comment]
@robons , @canwaf , @mikeAdamss Below is what I propose for when it comes to using Github Actions instead of Jenkins.

1. With Github Actions we can set up a CI/CD pipeline that does all the things our current pipeline does. To prove this, I did a small PoC which builds a python module and deploy to PyPI using GitHub Actions - see https://github.com/GDonRanasinghe/git-actions-poc.

2. In order for the pipeline to deploy to PyPI, we first create the PyPI project-scoped API Key. Then add this as a workflow secret to the git repo (see https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md). Finally, the pipeline's deploy stage will use this secret to deploy.

Note: as shown below, when using the API key to deploy, PyPI wants us to use __token__  as the username (see https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/). Otherwise the authentication will default to the user-based authentication and the deployment will fail.
```
name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          username: __token__
          password: ${{ secrets.test_pypi_password }} <-- test_pypi_password is the name of the github secret containing the pypi api key.
          repository_url: https://test.pypi.org/legacy/
```

GitHub Actions allow triggering pipelines on various events and covers all the events provided by Jenkins (see https://docs.github.com/en/actions/using-workflows/triggering-a-workflow and https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows). For us, below events would be sufficient.

However, I suggest we stop running verification checks when a new branch is created because this is redundant - we are doing all the verification checks on creating a PR and on PR merge. What are your thoughts on this?
```
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    branches:
      - "*"
```

I've also investigated what impact the use of Github Actions has on security and the use of our resources by non-collaborators (i.e. external users/public).
1. The default moderation settings in Github (see attached 1st image) do not allow external users to push to the repos.

2. If an external user wants to submit a PR, they can do so by forking our repo and submitting a PR from the forked repo to ours.

3.  When that PR is submitted, Github asks the moderator of the repo (i.e. us) to approve the running of the GitHub Actions workflow triggered by the PR. So this means, we can allow external users to fork and create PRs whilst not allowing them to use our resources without our approval (see the attached 2nd screenshot).

But there is a caveat to the above:

- Once we approve an external user's first request for running a GitHub Actions workflow and merged his PR, this external user will become a collaborator of the repo. Because this user is now a collaborator, the subsequent PRs this user is going to submit will NOT need our approval for running the workflows. Therefore, the subsequent PRs from this user is going to use our resources.

- Above caveat could lead to secret exfiltration as well: if the external users try to print the secrets to the workflow logs which they can view via github.com, GitHub automatically redacts them (see https://docs.github.com/en/actions/security-guides/encrypted-secrets#accessing-your-secrets).  But there could be other means for exfiltrating (e.g. sending the secret to a web api during the github action workflow).

- I've also checked in the internet for any suggestions on how to resolve this caveat. But I did not find any. Maybe another one of us should check as well?

I've also had a brief look at the Deploy Keys feature provided by GitHub. It looks like this is will not suit us due to its cons (see https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys).

**Whats Next?**
So from what I can see, GitHub Actions is a nice replacement for Jenkins but there is the above caveat. Maybe we have some sort of an internal process that verifies new collaborators to our repo? If so, will this process make the above caveat a non-issue for us?

What do you guys think about the next steps on this? As mentioned in the ticket, the changes we are going to decide here will affect all the repos in GSS-Cogs org. So my recommendation would be to present our findings to the wider team and get their opinion. Also, we might be able to find a resolution to the above caveat.

**Comment by GDonRanasinghe** [comment]
Discussed above with @robons . As per the next immediate step, I am going to check whether Env secrets can be utilised to address the caveat above.

**Comment by GDonRanasinghe** [comment]
Quick update on the above: GitHub provides a setting for making the approval for running workflows mandatory for all the PRs submitted by external users regardless they are first-time users of not.  So every time an external user creates a PR, it asks us to approve the running of workflow. When approving we need to make sure that we review the code for any exfiltrating of secrets, and whether the PR is worth for using our resources. This is the solution to the above caveat I've mentioned.

![Screenshot 2022-05-13 at 11.08.24.png](https://images.zenhubusercontent.com/6202658f9afc98f97d963263/ac6ea361-c7c1-49ba-b18f-10c24b835e56)

**Comment by GDonRanasinghe** [comment]
**Presenting test results:**

Github Actions does not provide this feature out of the box but we can use a free action from the GitHub Actions Marketplace: https://github.com/marketplace/actions/publish-unit-test-results

**Comment by GDonRanasinghe** [comment]
@robons Given the below note in the ticket description, what do you think is the next best step or the output for this ticket?

> N.B. this almost certainly needs discussion with the wider team in the architectural meeting/the monthly (?) tech board before progressing.

**Comment by robons** [comment]
> Since our jobs will run independent on reviewer approval, we will not be impacted by this. If the self-hosted runner needs an explicit approval for running a queued job (I believe not), we should be able to adjust this on the runner end (e.g. GCP).

Say someone created a fork and created a PR to fix a bug, given that we will have restricted actions so they only run on approval for these kind of PRs, will we have to do anything to reschedule the github action?

> Given the below note in the ticket description, what do you think is the next best step or the output for this ticket?

I've linked the https://github.com/GSS-Cogs/csvcubed-pmd/issues/1 issue to this ticket and I think it's a good next step we can take in the investigation of this topic. 

> N.B. this almost certainly needs discussion with the wider team in the architectural meeting/the monthly (?) tech board before progressing.

Yes, before we end up going too deep into this, could you bring this all together and do a short 5-10 min presentation to the next architecture meeting (perhaps not today's but next week's?) so we can just report our findings to the rest of the team. 

I think it'd be worth at that point recommending that we set up a GCP github action runner (explaining why we want to do this rather than just relying on the free ones) so we can get a bit of buy-in before we do that part of the work.

------

Thanks for the detailed work you've done here, it's certainly helped clarify in my mind the security concerns we had about secret exfiltration and automatic builds on our local runners. I imagine these parts will feed into some later documentation on things to watch our for in external fork PR reviews.

**Comment by GDonRanasinghe** [comment]
@robons Thanks for the feedback, I will make sure to action on those next steps.

**Comment by GDonRanasinghe** [comment]
> Yes, before we end up going too deep into this, could you bring this all together and do a short 5-10 min presentation to the next architecture meeting (perhaps not today's but next week's?) so we can just report our findings to the rest of the team.

Sure, I will get a presentation ready and will present at the next architecture meeting.

**Comment by GDonRanasinghe** [comment]
@robons I've changed the estimate on this to 13 as I have added some new tasks to this ticket that were not in here when the original estimate was done. I think 13 is a true reflection of the effort involved in this ticket.

**Comment by GDonRanasinghe** [comment]
@robons , @mikeAdamss I've got a response from GitHub for my question on API calls limits when using GitHub Actions. As we expected, this limit refers to the calls made to GitHub REST API (see below).

	
Paul (GitHub Support)
May 19, 2022, 11:11 AM UTC

> Hi Gishan,
> 
> Thank you for writing to GitHub Enterprise Support.
> 
> Apologies for taking a while to get back to you.
> 
> That rate limit applies when you are using the GITHUB_TOKEN available in the workflow run to make API calls to GitHub's APIs (REST or GraphQL). You can make as many API calls as you need to other external APIs.
> 
> Let me know if you have any further questions.
> 
> Regards,
> Paul
> GitHub Support

**Comment by GDonRanasinghe** [comment]
The slides are attached.

[https://app.zenhub.com/files/374709947/a08f5714-5820-4622-8f3b-cd2ad348f0dc/download]
(https://app.zenhub.com/files/374709947/a08f5714-5820-4622-8f3b-cd2ad348f0dc/download)

**Comment by GDonRanasinghe** [comment]
Guide for migrating from Jenkins to GitHub Actions: https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-jenkins-to-github-actions
