### ISSUE TITLE
Investigate conversion of code-list-config.json format to JSON-LD

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#488]
Assuming that we're going to create a new MAJOR version of the code-list-config.json format for this movement to JSON-LD:

- Figure out and document:
  - [ ]  how the code-list-config.json document will need to change.
    - [ ] Update to schema v2.0
    - [ ] Add default `@context` value of [RDF-A11 JSON-LD context](http://www.w3.org/2013/json-ld-context/rdfa11)
    - [ ] Allow additional properties to be defined within the main ConceptScheme object as well as additional concepts.
  - [ ] how the JSON-LD predicates and values will be interpreted in different sections of the document (i.e. will concept triples be written with the concept as the subject of the triple or will it be something else? similarly for the properties expressed at the top level with the catalogue metadata: do they get serialised against the concept scheme or the dcat catalog record?).
   - [ ] How we will likely need to change the csvcubed code base to ensure this information is persisted to RDF correctly (via the CSV-Ws) - for concepts, does this mean we add an extra column in the CSV file, and can everything else go in the CSV-W's JSON-LD document?
   - [ ] Whether we need to alter the csvw2pmd Jenkins pipeline at all to support this. 
     - [ ] Investigate how to achieve this.
  - [ ] Do we want to bring this information back via the Inspect API, and how would this be achieved?
  - [ ] Detail the documentation to be created and what should be included in this.
  - [ ] Consider what test cases need to be written.
 - [ ] Create the tickets needed to complete the necessary work.

See the comment below for an example of a practical implementation.

**Comment by robons** [comment]
See the attached ZIP file which contains some code which is capable of treating a code-list-config.json file as JSON-LD (whether the user has set a `@context` or not) and is capable of extracting the additional RDF which the user has added to the document.  

[https://app.zenhub.com/files/374709947/ca42ff9a-7cc2-447f-b93c-2c2123c4b9e9/download](https://app.zenhub.com/files/374709947/ca42ff9a-7cc2-447f-b93c-2c2123c4b9e9/download)

We see that the main object has had the type set to `"@type": "dcat:Dataset",`. It makes sense that this triple would be attached to the primary `skos:ConceptScheme` record.

We also see that one of the concepts (England) has an additional `rdfs:label` specified:

```json
"rdfs:label": {
    "@value": "Lloeger",
    "@language": "cy"
}
``` 

The script contained within the ZIP file can then interpret the whole JSON file and prints out the triples which aren't currently understood by csvcubed:

```bash
$ python extract-additional-rdf.py 
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://example.com/concept-scheme/this-one> a dcat:Dataset .

<http://example.com/concept-scheme/this-one/concepts/E92000001> rdfs:label "Lloeger"@cy .
```

**Comment by SarahJohnsonONS** [comment]
- Define and publish a default context (e.g. 488-codelist-jsonld/new/codelist_context.json)
- Incorporate qb and csvw prefixes into the published context so that column definitions can be populated
- Identify which triples need @id to be generated from the files provided so that triples can be constructed correctly
- Develop new functions (or modify existing functions) to ensure that concepts can be sorted correctly according to the config file (sort is an instruction to csvcubed rather than a true predicate) - also need to ensure that concept hierarchy is being persisted correctly
- Update reusable-rdf-resources (e.g. licenses.json and organisations.json) so that values are recognised in the config file
- Issues encountered during investigation - @id for dcat:theme, rdfs:label and rdfs:comment not being correctly expanded when using rdflib graph.serialize
