### ISSUE TITLE
Come up with a diagram of how csvcubed + sister packages fit together and work

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#561]
- [ ] Also need to describe one-level-down what the different modules of each package are for and how they interact with each other.

This was decided on at the last sprint retro

Focus on the key bits of infrastructure here and come up with a proposed style in this spike. Don't have to cover absolutely everything, but should cover the core stuff and can be extended once we agree in which direction we should go with it.

**Comment by robons** [comment]
Created some initial stuff in a miro board: https://miro.com/app/board/uXjVPeHESx8=/

**Comment by CharlesRendle** [comment]
Diagram looks good. Very easy to follow each section with a logical progression to each subsequent box (assuming top left start).

I had a few questions while reading but was able to find the answers myself by following links to repositories/documentation pages which is good indication. However, I do reflect a slight bias as I am somewhat familiar with the link destination pages and therefore had a bit of a head start knowing what to look for in order to answer my queries.
