### ISSUE TITLE
[BUG] `from_existing` values which are not numerated result in frustrating WARNING spam

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#715]
Thank you for taking the time to file a bug report. Before creating a new issue, please ensure you have read [our bug reporting guidelines](https://gsscogs.github.io/csvcubeddocs/external/guides/raise-issue/#report-bugs) as well as checking the open issues for existing issues regarding your bug.

IF type is specified, return only suggestions for that type instead of the above.

**Describe the issue:**
When using a URI which isn't enumerated from a `from_existing` list, you get absolutely spammed with all the different options creating a massive flow chart of text which requires detailed analysis to figure out what the problem is.

**Reproducible steps / Code example:**
For example, for the Pret data (sample csv attached, version locked json linked)

[pret.csv](https://github.com/GSS-Cogs/csvcubed/files/10546516/pret.csv)
[pret.json](https://github.com/GSS-Cogs/ons-faster-economic-indicators/blob/a66680edc3a19e90372539c08764d25b04a48579/pret/pret.json)

`csvcubed build pret.csv --config pret.json`

**Error message obtained / Resulting behaviour:**
Generates a very long warning (not the full warning, but the relevant one)

```2023-01-31 12:10:23,155 - csvcubed.cli.build - WARNING - Schema Validation Error: $.columns.Value - Unable to identify {'type': 'observations', 'data_type': 'decimal', 'measure': {'label': 'indexed sales', 'description': 'indexed weekly sales indexe…

    If you meant to declare 'This column represents a dimension of the cube', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'dimension' was expected

    If you meant to declare 'This column represents an attribute (with resource values) of the cube (creating a new attribute)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'attribute' was expected

    If you meant to declare 'This column represents an attribute (with resource values) of the cube (reusing an existing attribute definition)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'attribute' was expected

    If you meant to declare 'This column represents an attribute (with literal values) of the cube', then:
        - Additional properties are not allowed ('measure', 'unit' were unexpected)
        $.type - 'attribute' was expected

    If you meant to declare 'This column represents the phenomenon which has been measured (defining new measures)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'measures' was expected

    If you meant to declare 'This column represents the phenomenon which has been measured (reusing existing measure definitions)', then:
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)
        $.type - 'measures' was expected

    If you meant to declare 'This column holds observed/recorded values', then:
        $.measure.from_existing - 'https://purl.org/csv-cubed/resources/measures#indexed-sales-value' is not recognised by csvcubed.

    If you meant to declare 'This column represents the unit of measure in which observations were recorded (defining new units)', then:
        $.type - 'units' was expected
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)

    If you meant to declare 'This column represents the unit of measure in which observations were recorded (reusing existing unit definitions)', then:
        $.type - 'units' was expected
        - Additional properties are not allowed ('data_type', 'measure', 'unit' were unexpected)

    If you meant to declare 'This column will be present in the CSV but will not be converted to RDF', then:
        - {'type': 'observations', 'data_type': 'decimal', 'measure': {'label': 'indexed sales', 'description': 'indexed weekly sales indexed ((Friday 3 Januar…
        - False was expected (build.py:101)
```

**Expected behaviour:**
The actual problem with the config file is that the measure `"from_existing": "https://purl.org/csv-cubed/resources/measures#indexed-sales-value"` config isn't enumerated in the qube-config json schema. The warnings should assume that the user assigns the `"type": "blah"` correctly, and provide the specific warning, instead of all possible warnings.

i.e. The column is configured correctly and the only relevant part of the warnings above is:
```
    If you meant to declare 'This column holds observed/recorded values', then:
        $.measure.from_existing - 'https://purl.org/csv-cubed/resources/measures#indexed-sales-value' is not recognised by csvcubed.
```

**Additional Information:**
Please feel free to add any additional information which may be useful to diagnose the issue.

**Version information + Operating System:**
csvcubed 0.2.1, python 3.10.3, MacOS 13.2

**Comment by CharlesRendle** [comment]
Attempting Triage:

- Impact = **Very Low (1)** - Quirk which isn't quite ignorable because of the mass of text but the workaround necessary is extra analysis.
- Probability = **High (4)** - Mostly a guess at the frequency `from_existing` is used.

- Combined Score = **4** == **Tolerable** - Highest end of tolerable

@robons what do you think?

**Comment by robons** [comment]
I think the probability score is maybe too high. To be perfectly honest I'd say the probability should be low/very low given how few users this affects (and even then how few data sets it applies to).

I'd argue that the `Impact` isn't high enough though. Since there isn't technically a workaround, it doesn't really fit in with the examples we have;  but I would rate the impact as `annoying` so I'd be tempted to put it between Moderate and High.

**Comment by CharlesRendle** [comment]
Not sure if this needs to be in a new ticket or an edited continuation of this. Best of both worlds(?) I'm going for a comment.

Giving this a spike label for now as during refinement we could only narrow down the location of the printable warnings to `jsonvalidationerrors.py`

From here we would want to investigate whether it is possible to use the column type information to print a more specific warning instead of chucking all of them at the user.

Adding unit tests to display the reduced amount of spam.


**Note** happy for this to be re-discussed/re-estimated in a later refinement session.

**Comment by robons** [comment]
This ticket involves working in the [csvcubed.utils.validators.schema]() module. Rob recommends, **when the error path is `$.columns` inside a JSON file which adheres to the qube-config.json schema**, that we alter `map_to_internal_validation_errors` so that when we generate an instance of `AnyOneOfJsonSchemaValidationError`, we only pass in `possible_types_with_grouped_errors` where the list of possible types/errors has been filtered down to the ones relevant to the `type` property the user wrote in their column definition (if it's present).

**Comment by robons** [comment]
The behaviour your now get when using an unknown existing dimension is as follows:

```
csvcubed build data.csv --config from_existing_dim_not_in_enum.json
2023-02-20 12:50:08,184 - csvcubed.cli.build - WARNING - Schema Validation Error: $.columns.Dim-2 - Unable to identify {'type': 'dimension', 'label': 'Trade Direction Dimension', 'code_list': True, 'from_existing': 'http://example.com/dimensions/tra…

    If you meant to declare 'This column represents a dimension of the cube', then:
        $.from_existing - 'http://example.com/dimensions/trade-direction' is not recognised by csvcubed.
 (build.py:101)
Build Complete @ /Users/HA9WF3CZ/Code/csvcubed/tests/test-cases/readers/cube-config/v1.0/schema_validation_errors/out
```
