### ISSUE TITLE
Changes to reusable-test.yaml broke main-push.yaml

### ISSUE THREAD

**Issue by SarahJohnsonONS** [GSS-Cogs/csvcubed#836]
Incorporating the pandas version 1.x/2.x into the `test_in_environments` job caused the `main-push` workflow to break as there was no `pandas-version` variable added.

Triage:
Impact: 4 - currently, the `main-push` GH Action will always fail as it can't run the `test_in_environments` job without a `pandas-version` variable being specified
Probability: 2 - only affecting Features Squad, as branches are still merged into main even if the workflow fails. Hopefully it's unlikely that there would be significant errors in the branch being merged into main if workflows had passed during the PR process but we probably shouldn't assume too much.

**Combined score 8 (important bug)**

**Comment by robons** [comment]
I'm not sure we should triage bugs that occur unless those bugs can be replicated in a version of csvcubed which has been released. If the bug hasn't made it out in a release yet, then we should hold off on releasing until either:

* The bug has been fixed in main released,
* The change which caused the bug has been reverted in main.
